# File: .golangci.yml

version: "2"

run:
  modules-download-mode: readonly

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - govet
    - grouper
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

  disable:
    - wrapcheck
    - errcheck
    - exhaustive
